version: '3.9'

services:
  test-db:
    container_name: test-db
    image: postgres:14.5
    ports:
      - "5432:5432"
    shm_size: 1G
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    volumes:
      - test-db:/var/lib/postgresql/data

volumes:
  test-db: